### PR TITLE
Para view57

### PR DESCRIPTION
**Pull request by CharlesGueunet**
Dear Julien,
This PR  changes the CMake architecture in order to build TTK against the current versions of VTK & ParaView.

These changes does not impact how the user build TTK (except that he should have an up to date VTK/ParaView of course).

As you can see [here](https://markmail.org/thread/cu2wyqpvporqvps6), important changes have been made on the VTK build system, impacting ParaView and every VTK based applications. The way VTK is linked to a project is now more modular and relies on a `vtk.module` file in order to declare dependencies. I have used a similar syntax for TTK, using a `ttk.module` file.

I will update the Guideline to explain in detail the new TTK architecture.

Charles

### CODE REVIEW

**Comment by julien-tierny** [comment]
hi charles,

thanks a lot for this great work.

it seems that some work is still needed at the installation level:
- [ ] the R-path is broken in the installed ParaView plugin (*so files)
- [ ] the ParaView variable VTK_INSTALL_PREFIX no longer exists in ParaView. it was used to install the TTK ParaView plugin in an adequate default location. a replacement needs to be found
- [ ] the builtin examples do not work anymore, for a related reason. The ParaView variable VTK_INSTALL_DATA_DIR (used in the paraview/patch/ files) does not seem to exist anymore.

at the source tree level:
- [ ] the ParaView GUI XML specification should not be outside of the "paraview/" directory. thanks for finding a way to move them back to paraview/

cheers,
julien
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
also, please see @lhofmann's messages in issue #248 for vtk8 and vtk9 support, as well as examples for travis support for vtk9/pv5.7.
cheers
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by lhofmann** [comment]
I had a quick look at the changes here. Do I understand correctly, that you are dropping support for the "legacy" build systems of ParaView<5.7 and VTK<9?

**Comment by julien-tierny** [comment]
I believe it would be better indeed to still support the legacy
vtk/paraview (just for the sake of backwards compatibility).
Please feel free to adjust.
--

**Comment by julien-tierny** [comment]
Closed (to be re-created)

**Pull request closed without merging**
