### PR TITLE
Changes for compiling on Windows 10 with MSVC14.

### PR DESCRIPTION
**Pull request by atritty**
Hi
It's a new pull request. I hope it'll help to identify changes.

### CODE REVIEW

**Comment by julien-tierny** [comment]
hi, 
this is so much better! thanks!
I'll process this ASAP.
cheers,

**Comment by julien-tierny** [comment]
hi, 
for your information, I tested your pull request on linux with our batch of test examples and I observed no bug or regression. so far, so good!
I'll move on now to the proof-reading of your edits.
cheers

**Comment by julien-tierny** [comment]
hi Alexey,

I have tested your branch on the following configuration:
- Windows 7 (in a virtualbox)
- MSVC15
- Python36 (instead of Python27, future releases of TTK will depend on the 3.6 version)

overall, things went smoothly, except for three things:

1) ParaView patch error
=
When applying the ParaView patch as suggested in your notes, I obtain the following error message:
"
c:\ttk\paraview\patch>patch-paraview-msvc-x86.cmd c:/paraview
Patching ParaView sources for compiling on MSVC x86
error: patch failed: ThirdParty/cgns/vtkcgns/src/adf/ADF_internals.c:213
error: ThirdParty/cgns/vtkcgns/src/adf/ADF_internals.c: patch does not apply
"
it seems that something went wrong here.

generally speaking, I would not recommend to release a patch set meant to be applied on a nightly repository (https://gitlab.kitware.com/paraview/paraview.git). this repository is meant to be alive. a patch that is working today may become buggy tomorrow due to edits in this repository.

instead, I would recommend to write the patch for one specific release of ParaView (for which the source code is not meant to change anymore). typically, I would recommend to write patches against the latest stable version of ParaView (5.4.1)
Can you update that?

2) ParaView patch content
=
the current release of TTK also comes with a patch set for ParaView (paraview/patch/patch-paraview-5.4.1.sh). the purpose of this patch set is twofold:
a) apply some TTK branding (to make the TTK demos available in the example menus)
b) fix a few things in ParaView to enable further TTK features in the plugin (like sequentially ordered point selection for FiberSurfaces)

the patch "paraview/patch/patch-paraview-msvc-x86.cmd" does not seem to take that into account at all.
would it be possible to also port the content of the patch "paraview/patch/patch-paraview-5.4.1.sh" in "paraview/patch/patch-paraview-msvc-x86.cmd"?

3) Default install directory for TTK plugins
=
ParaView scans a specific directory to search for installed plugins. By default, a typical value under windows is "C:\Program Files\ParaView\bin\plugins".
TTK needs to know this path in order to install its plugins in the right path.
This path is stored in the CMake variable TTK_INSTALL_PLUGIN_DIR
Under Linux, this path can be determined automatically: see line 37 of paraview/CMakeLists.txt
This detection seems to fail under windows (and the user currently needs to set TTK_INSTALL_PLUGIN_DIR manually with cmake-gui)
Would it be possible to fix that?

Remarks
=
Other than this, I found that I had to update the PATH variable for several other packages (Python36, Qt, ParaView, ParaView plugins, etc). Also, OpenGL2 is not supported by VirtualBox. As a consequence, I could not display any scene with ParaView (I could run some TTK code by activating the spreadsheet view right from the start though).

**Comment by atritty** [comment]
Hi
1. Did you obtain this error on Windows7 in VirtualBox?
Windows7 x64 or x86?
2. I'll try to create an analogue of patch-paraview-5.4.1.sh for Windows
3. I see that it's because CMake can't determine value of VTK_INSTALL_PREFIX I'll add changes for Windows
How to add new changes (patch and default install directory for TTK plugins)? Create a new pull request?

**Comment by julien-tierny** [comment]
hi,

> 1. Did you obtain this error on Windows7 in VirtualBox?
yes
> Windows7 x64 or x86?
it was windows 7 x64

> 2. I'll try to create an analogue of patch-paraview-5.4.1.sh for Windows
that'd be great!

> 3. I see that it's because CMake can't determine value of VTK_INSTALL_PREFIX
> I'll add changes for Windows
awesome

> How to add new changes (patch and default
> install directory for TTK plugins)? Create a new pull request?
no need to create a new pull request.
keep on pushing your edits to your branch and future commits should be taken 
into account upon the merge of the current pull request. 
github works beautifully in that regard.
you'll need to pull first (git pull) because I already pushed a few edits on 
your branch.

thanks for letting me know if you have any issue.

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universites UPMC - LIP6
http://lip6.fr/Julien.Tierny

**Comment by atritty** [comment]
Hi
I added in my branch: a new patch for Windows, a changing in paraview\CMakeLists.txt and new changes in installation notes (default install directory for TTK plugins and patch-paraview-5.4.1.sh are working with this notes)
About patching error (patch-paraview-msvc-x86.cmd): I obtained the error only on second start patching command (Windows7 / Windows10) and there were no any errors on first start.

**Comment by julien-tierny** [comment]
hi,

thanks a lot for these commits!

> install directory for TTK plugins and patch-paraview-5.4.1.sh are working
> with this notes) 
your new installation notes mention a patch named "patch-paraview-
msvc-5.4.1.sh" but I'm afraid you haven't added it to the github repository.
please do "git add " on this file prior to committing (git commit) and pushing 
(git push).
thanks!
julien
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universites UPMC - LIP6
http://lip6.fr/Julien.Tierny

**Comment by atritty** [comment]
Hi
patch-paraview-msvc-5.4.1.sh is wrong name in notes (I already changed it in a new commit).
I tested patching with existing patch (patch-paraview-5.4.1.sh)

**Pull request merged**
