### PR TITLE
Update PersistenceDiagramClustering, DistanceMatrix with new PersistenceDiagram structure

### PR DESCRIPTION
**Pull request by pierre-guillou**
As a follow-up to #745 (and as a complement to #803), this PR makes the `PersistenceDiagramClustering`, `PersistenceDiagramDistanceMatrix` & `PersistenceDiagramAuction` modules use the new PersistenceDiagram structure defined in core/base/PersistenceDiagram/PersistencDiagramUtils.h instead of a templated `std::tuple` (which is quite harder to understand & manipulate). Within this new data structure, a boolean field identifies infinite pairs that can be produced by the DiscreteMorseSandwich algorithm.

The unified PersistenceDiagram data structure also allows to de-template the code in the concerned base layer modules, leading to better parallelism during the build process and more precise code lint and static code analysis with `clang-tidy`.

In `PersistenceDiagramAuction`, the `GoodDiagram` and `BidderDiagram` data structures have been respectively aliased to `std::vector<Good>` and `std::vector<Bidder>` to further reduce their footprint in terms of LoC.

A lot of commented code in the base layer has also been removed.

Per diagram aggregated matching costs has been added as FieldData to the Clustered Diagrams and Cluster Centroids outputs. The global cost is already present on the FieldData of the Matchings output.

No change is to be expected on the two ttk-data state files that use these modules. However, newly added matchings costs should change the outputs of the corresponding Python scripts.

Enjoy,
Pierre

### CODE REVIEW

**Comment by julien-tierny** [comment]
can you please git pull the main repo to get the MacOS CI hotfix on your PRs?

**Comment by julien-tierny** [comment]
The code looks good, I'll merge it for now, but the CI for the python scripts report hash differences for the output of the persistence diagram clustering demo. To be double-checked.

**Comment by pierre-guillou** [comment]
Yes, that's expected: there's new data on the matchings output (costs). I'll file a ttk-data PR with the new hashes soon.

**Comment by julien-tierny** [comment]
awesome, thanks!

**Pull request merged**
