### PR TITLE
DilateErode 2.0

### PR DESCRIPTION
**Pull request by JonasLukasczyk**
Hi Julien,
this PR adds a new module named `DilateErode` that allows you to assign a pivot label to all neighbors (dilate), or override a pivot label with the largest neighbor label (erode). You can also adjust the number of performed iterations. This is useful in many image-segmentation and tracking tasks. I'm also working on a new module called `TrackingFromLabels` which will get its own PR. Then I will create a new statefile that demonstrates these two filters, but I would prefer to merge these filters in first.

Best
Jonas

### CODE REVIEW

**Comment by JonasLukasczyk** [comment]
I don't understand the following CI issue with the Python layer. Can someone help me out (@pierre-guillou)?

Starting: Test Python Example
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.182.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/3fd98151-c9d9-4774-b08f-cda7b53651e6.sh
Traceback (most recent call last):
  File "./example.py", line 30, in <module>
    from topologytoolkit import (
  File "/home/vsts/work/1/a/ttk-install/lib/python3.6/site-packages/topologytoolkit/__init__.py", line 70, in <module>
    from .ttkDilateErode import *
ImportError: /home/vsts/work/1/a/ttk-install/lib/python3.6/site-packages/topologytoolkit/ttkDilateErode.so: undefined symbol: PyttkAlgorithm_ClassNew
##[error]Bash exited with code '1'.

**Comment by pierre-guillou** [comment]
Hi Jonas,
can you try with the VTK layer inheriting from the base layer (`ttk::DilateErode`) with `protected` instead of `public`? We had an issue like this one last year.

**Comment by JonasLukasczyk** [comment]
Thank you for the fast reply! I'm trying it right now.

**Comment by JonasLukasczyk** [comment]
That did the trick, thanks @pierre-guillou! That is good to know.

**Comment by julien-tierny** [comment]
hi jonas, thanks a lot for your pr.
could you please provide a ttk-data state files that testes/documents it?
cheers

**Pull request merged**
