### PR TITLE
+ HelloWorld standalone; +ttkUtils.cpp to fix linking issue

### PR DESCRIPTION
**Pull request by JonasLukasczyk**
Hi Julien,
this PR adds a HelloWorld standalone module, and fixes the ttkUtils linking error by moving the function implementations to a cpp file (this was not possible with the previous cmake architecture).

Best
Jonas

### CODE REVIEW

**Comment by JonasLukasczyk** [comment]
I noticed Charles opened a similar PR (#353 ), but my PR already includes the continuous integration fix, the new ttkMacro.h file (instead of macros.h of the old API), and HelloWorld in general has more error handling/documentation. So I guess we can close #353 and focus on this PR.

Best
Jonas

**Comment by JonasLukasczyk** [comment]
To be more clear: this PR does everything that #353 does and more.

**Comment by JonasLukasczyk** [comment]
Currently this PR fails to build on windows with the same issue encountered in Charles's PR (#353 ) (see error below).

It seems that on windows if the functions of ttkUtils are implemented in a separate file they are not correctly exported (can not be linked against). @CharlesGueunet do you think this is a problem of the cmake structure?

One quick-fix I will try for now is to use a class instead of a namespace.

```
FAILED: bin/ttkExtract.dll lib/ttkExtract.lib 
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=core\vtk\ttkExtract\CMakeFiles\ttkExtract.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100177~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100177~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\ttkExtract.rsp  /out:bin\ttkExtract.dll /implib:lib\ttkExtract.lib /pdb:bin\ttkExtract.pdb /dll /version:0.0 /machine:x64 /INCREMENTAL:NO   && cd ."
LINK: command "C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\ttkExtract.rsp /out:bin\ttkExtract.dll /implib:lib\ttkExtract.lib /pdb:bin\ttkExtract.pdb /dll /version:0.0 /machine:x64 /INCREMENTAL:NO /MANIFEST /MANIFESTFILE:bin\ttkExtract.dll.manifest" failed (exit code 1120) with the following output:
   Creating library lib\ttkExtract.lib and object lib\ttkExtract.exp
ttkExtract.cpp.obj : error LNK2019: unresolved external symbol "int __cdecl ttkUtils::replaceVariables(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class vtkFieldData *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (?replaceVariables@ttkUtils@@YAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVvtkFieldData@@AEAV23@2@Z) referenced in function "protected: virtual int __cdecl ttkExtract::RequestData(class vtkInformation *,class vtkInformationVector * *,class vtkInformationVector *)" (?RequestData@ttkExtract@@MEAAHPEAVvtkInformation@@PEAPEAVvtkInformationVector@@PEAV3@@Z)
ttkExtract.cpp.obj : error LNK2019: unresolved external symbol "int __cdecl ttkUtils::stringListToVector(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > &)" (?stringListToVector@ttkUtils@@YAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@3@@Z) referenced in function "protected: virtual int __cdecl ttkExtract::RequestData(class vtkInformation *,class vtkInformationVector * *,class vtkInformationVector *)" (?RequestData@ttkExtract@@MEAAHPEAVvtkInformation@@PEAPEAVvtkInformationVector@@PEAV3@@Z)
ttkExtract.cpp.obj : error LNK2019: unresolved external symbol "void * __cdecl ttkUtils::GetVoidPointer(class vtkDataArray *,__int64)" (?GetVoidPointer@ttkUtils@@YAPEAXPEAVvtkDataArray@@_J@Z) referenced in function "protected: virtual int __cdecl ttkExtract::RequestData(class vtkInformation *,class vtkInformationVector * *,class vtkInformationVector *)" (?RequestData@ttkExtract@@MEAAHPEAVvtkInformation@@PEAPEAVvtkInformationVector@@PEAV3@@Z)
bin\ttkExtract.dll : fatal error LNK1120: 3 unresolved externals
```

**Comment by JonasLukasczyk** [comment]
Switching to a class did not work. It seems windows finds the function declarations, but not the implementations. If we can not fix this issue with the cmake structure, I could also move the static functions to ttkAlgorithm (now non static). I guess this will solve the issue, but requires a lot of engineering (for the classes currently not using the new API) so we should all be on board before I go down that road.

**Comment by julien-tierny** [comment]
hi jonas,

thanks for your input!

please split this PR into 2:

- 1 for fixing issue #351 (this one can be merged quickly as soon as it's fixed)
- 1 for the new helloworld standalone (this one requires discussion)


regarding your new standalone suggestion:

a few pros:
+ I like the fact that's it more compliant to VTK (indeed less code to maintain for us -> good)
+ I like its conciseness 

a few things to change:
* please use ttk's command line parser though (instead of vtk's) as it set global default variables automatically (input, debug, thread), see (standalone/Blank/cmd/main.cpp) for an example
* please write all output port to disk (include port number in filename)

with the above two edits, your example will be fully compliant with the standalone currently sitting in ttk.

a few cons:
- ttk's current feature for standalone programs actually supports both core/base and core/vtk modules (see standalone/GeometrySmoother/cmd/main.cpp for a core/base example). your suggestion breaks the possibility to generate standalones independent of vtk.

a few open questions
? ttk also automatically creates standalone with a minimalist gui (see standalone/Blank/gui/main.cpp). should we keep on supporting those? @CharlesGueunet: what's your take? have you ever used those?

based on the outcome of this discussion, I will ask you to propagate these edits to all standalones.

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by JonasLukasczyk** [comment]
I will open a new PR with the discussed updates to HelloWorld standalone, and the ttkUtils linking error has already been resolved with PR #361 

Best
Jonas

**Pull request closed without merging**
