### PR TITLE
WIP: Unlock OpenMP on windows

### PR DESCRIPTION
**Pull request by CharlesGueunet**
Dear Julien,

This work in progess, once finished, will unleash the full power of OpenMP.... 2.0 on windows.
Ok, this is not so impressive now that we are reaching the 5.0 standard but hey... this is better than nothing :)
Still need some tests on Azure which seems to be dead on my side (only the interface).

Charles

### CODE REVIEW

**Comment by CharlesGueunet** [comment]
Will reopen later.

**Comment by pierre-guillou** [comment]
I think there is an alternative way to use OpenMP on Windows that does not rely on such heavy code modifications.

I have been trying for the past week to use [clang-cl](https://clang.llvm.org/docs/MSVCCompatibility.html), a modified version of clang to serve as a front-end to Microsoft's `cl.exe` compiler, and so far it has been able to build TTK with `TTK_ENABLE_OPENMP=ON` and execute the TTK examples, seemingly on several cores, on my Windows VM and on GitHub Actions.

To do so, you'll need the `C++ Clang tools for Windows` optional component of Visual Studio, as stated in [this Visual Studio documentation](https://docs.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=vs-2019), and configure & build TTK with:
```
cmake -DTTK_ENABLE_OPENMP=TRUE -G"Visual Studio 16 2019" -Tclangcl [project/dir]
cmake --build . --config Release --parallel
```
You might need to set the path to the directory containing the OpenMP runtime library (`libomp.lib`) ([somewhere around]( https://stackoverflow.com/questions/57209524/using-openmp-with-clang-and-cmake-in-visual-studio) `C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/Llvm/lib`.

In my packaging CI pipelines, I use [conda's openmp](https://anaconda.org/conda-forge/openmp) libraries though.

**Comment by julien-tierny** [comment]
does paraview also need to be built with clang-cl?
I'm asking the question to see if we need to edit ttk-paraview's packaging too?

**Comment by pierre-guillou** [comment]
No, I was using the standard Visual Studio build of ParaView. It seems that ParaView is not using OpenMP > 2.0 in its source code (or it may disable it on Windows like we do).

**Comment by JonasLukasczyk** [comment]
Does this PR still have a future?

**Comment by julien-tierny** [comment]
nope.
actually, openmp is enabled on windows builds thanks to clang :)

**Pull request closed without merging**
