### PR TITLE
ttkAlgorithm support for Implicit Triangulations

### PR DESCRIPTION
**Pull request by JonasLukasczyk**

### CODE REVIEW

**Comment by julien-tierny** [comment]
thanks jonas.

@CharlesGueunet
azure's virtual machine using make is now broken (it's been a few commit already). it's subsequent to the merge of some of jonas' latest features. 
any idea on how to fix it?

cheers
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by JonasLukasczyk** [comment]
I checked the build logs and it failed due to the cmake race condition Charles reported.

**Comment by CharlesGueunet** [comment]
hello guys,

You can find my fix for this race condition in CMake/VTKModule.cmake.
In your case, I see two hotfix.
The first one is to call make ttkAlgorithm-hierarchy manually before
calling make.
The second (still not clean) is to add the ttkAlgorithm-hierarchy target in
my hotfix.

Tell me if you find a better solution, but this could at least save you
some time for now :)

Charles

**Comment by julien-tierny** [comment]
@CharlesGueunet
can you please PR an azure fix for this?
thanks
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
thanks @CharlesGueunet!
cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Pull request merged**
