### PR TITLE
ContourTreeAlignment Doxygen Documentation

### PR DESCRIPTION
**Pull request by floWetzels**
Added doxygen documentation for the ContourTreeAlignment base module. The vtk layer documentatoin was already there. I also cleaned up namespaces for all internal classes and structures that are involved in the alignment computation, since this cluttered the doxygen Class List a lot. They are now all bundled in the ttk::cta:: namespace.

### CODE REVIEW

**Comment by julien-tierny** [comment]
ok, looks good. thanks!

**Comment by julien-tierny** [comment]
Could you also take into account my final remark from this PR please?
https://github.com/topology-tool-kit/ttk-data/pull/85

> One more thing, can you please update the doxygen documentation of the VTK layer classes involved in the examples of this PR, in order to include a link to the example? (and open a PR to TTK's code respository)

For that, please double-check this commit for an example:
topology-tool-kit/ttk@2b9fd4c

Thanks!

**Review by julien-tierny — CHANGES_REQUESTED** [review]
thanks for including a link to the online examples involved in your previous ttk-data PR.

**Comment by floWetzels** [comment]
I added the link, is it ok now? (sorry that it took so long...)

**Comment by julien-tierny** [comment]
looks good.
could you also add the link in the paraview xml file of the filter?
(see this commit for an example: https://github.com/topology-tool-kit/ttk/commit/2b9fd4c)

**Comment by julien-tierny** [comment]
@floWetzels 
this is a friendly reminder, could you add the link to the examples in the paraview xml file of the filter?
(see this commit for an example: [2b9fd4c](https://github.com/topology-tool-kit/ttk/commit/2b9fd4c))

**Review by julien-tierny — APPROVED** [review]

**Comment by julien-tierny** [comment]
alright, thanks!

**Pull request merged**
