### PR TITLE
New Reeb Graph algorithm

### PR DESCRIPTION
**Pull request by CharlesGueunet**
Dear Julien,

Here is a brand new parallel Reeb graph algorithm for TTK ! Using a task based approach similar to FTM, this method is based on a new algorithm described in my Ph.D. thesis.
The implementation has an API similar to the one provided by the FTM Tree filter, but deal with non-simply connected meshes as well as multiple connected components. 

Suggestion: Warning for the user when the mesh is a regular mesh to suggest FTM instead of FTR, as contour tree algorithms are more efficient?

Charles

### CODE REVIEW

**Comment by julien-tierny** [comment]
thanks @CharlesGueunet for this great addition!
can you fix real quick the code to make it pass the continuous integration?
thanks
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
hi charles,

thanks!

several files (not relate to FTR) have been touched by the commits of this PR:
- core/vtk/ttkFTMTree/ttkFTMTree.h
- core/vtk/ttkFTMTree/ttkFTMTree.cpp
- core/vtk/ttkFTMTree/ttkFTMStructures.h
- core/base/ftmTree/Structures.h
- core/base/ftmTree/Segmentation.h
- core/base/contourForestsTree/MergeTreeTemplate.h

are these edits necessary? what are they for?

also, it seems you forgot to remove some debug files from your PR ("bug.vtu" and "bug"). 
can you remove them?

last, for your information, ttk now has a .clang-format (cf #190).

thanks!
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by CharlesGueunet** [comment]
> several files (not relate to FTR) have been touched by the commits of this PR:
> - core/vtk/ttkFTMTree/ttkFTMTree.h
> - core/vtk/ttkFTMTree/ttkFTMTree.cpp
> - core/vtk/ttkFTMTree/ttkFTMStructures.h

FTM and FTR have structures in their wrappers with the same name (and purpose).
In order to avoid conflict, I have put these structures in namespace according to their corresponding base code. Even though the changes on FTM are not required as there is no conflict with the structure of FTR which have their own namespace, I find better for readability to have this consistency. 

> - core/base/ftmTree/Structures.h
> - core/base/ftmTree/Segmentation.h

These changes minor fixes that are not mandatory for FTR, but also to insignificant for a separate pull-request

> - core/base/contourForestsTree/MergeTreeTemplate.h

Wrongly commited, reverted in  b7f73aa653fa48ba313830e9efd1cc3979c9a6d3

> also, it seems you forgot to remove some debug files from your PR ("bug.vtu" and "bug").
can you remove them?

Removed from history

> last, for your information, ttk now has a .clang-format (cf #190).

Re-indent all FTR sources files in 13b6d941332865ce8c47373f5a2a87a15ac830b9

**Comment by julien-tierny** [comment]
thanks @CharlesGueunet for this great addition!
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
btw, can you update the warning messages of contour forests (to say it is now marked as DEPRECATED, in favor of FTR?)
thanks!
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Pull request merged**
