### PR TITLE
rename AtomicVector to the persepctive instance for ftmTree or ftmGraph

### PR DESCRIPTION
**Pull request by ollielo**
This is an amendment and replacement of #341 and #342. It renames AtomicVector to either FTMAtomicVector or FTRAtomicVector depend on which instance it is. Also update the include guard.

The deeper question for the core TTK developers is why do we have two essentially the same version of AtomicVector and AtomicUnionFind? Isn't **Do Not Repeat Yourself (DRY)** the first principle of good software engineering?

### CODE REVIEW

**Comment by julien-tierny** [comment]
hi,

sorry for the late reply but the situation is a little hectic here.

thanks a lot for your contribution to TTK!

> This is an amendment and replacement of #341 and #342.
@dbanesh 
I'm going to go ahead a close #342 then. 
thanks for confirming you're ok with this.

> It renames AtomicVector to either FTMAtomicVector or FTRAtomicVector depend on which instance it is.
thanks, looks good to me.
@CharlesGueunet: can you double-check this is OK for you too?

> why do we have two essentially the same version of AtomicVector and AtomicUnionFind? 
looks like some mutualization could happen here indeed.
@CharlesGueunet: any thought on that?

regarding commmit be34c3411b1151a494a24ea6b7f6e1ab9d41df51:
the purpose of the "examples" directory is to show how to put together a simple ttk pipeline (always the same one, taken from the companion paper) for the different APIs supported by ttk. 
so it short, it shows how to integrate ttk in an external program.

its purpose, as it currently stands, is not to exemplify all the features of ttk. ttk-data/states/ (https://github.com/topology-tool-kit/ttk-data/tree/dev/states) serves that purpose.
so I would recommend to remove that commit from the PR.

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by CharlesGueunet** [comment]
> can you double-check this is OK for you too?

This PR is all right for me too.

> looks like some mutualization could happen here indeed.
any thought on that?

Agreed, this would be helpful especially when bug are fixed (like the one on the const iterator) and would make this container more available for every developer.

Not related to this MR, the save and load function used here to read and write OFF could also be mutualized for every TTK module to use. This way, even the TTK OFF Reader / Writer could use them.

**Comment by ollielo** [comment]
@julien-tierny 

Thanks a lot for the feedback.

I agree that the added example is not necessary for the MR. I put it in as a way to communicate with Divya on a working example/test.

**Comment by ollielo** [comment]
@julien-tierny 

We also found some mysterious seg faults when FTRAtomicVector is destroyed, especially when T = SuperArc (which contains its own std::vector via SuperArc). When the Vector is destroyed, the destructor of std::vector is called on invalid instances o std::vector and causes seg fault. I am stilling trying to figure out why there are those invalid instances but Is suspect the problem comes from reserve() v.s. resize() (and how AtomicVector override, confuses them).

**Comment by dbanesh** [comment]
@julien-tierny confirming to please close out #341 and #342 given this PR.

**Comment by julien-tierny** [comment]
> I agree that the added example is not necessary for the MR. I put it in as a way to communicate with Divya on a working example/test.
@ollielo
can you please remove commit be34c34 from the PR?
I'll go ahead and merge after that.

thanks
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by ollielo** [comment]
@julien-tierny 

Changes to examples were backed out. Please review.

**Comment by julien-tierny** [comment]
alright, looks good to me.

thanks a lot for your contribution to TTK.
may that be the first of many :)

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Pull request merged**
