### PR TITLE
turned ttkUtils into class

### PR DESCRIPTION
**Pull request by JonasLukasczyk**
Hi everyone,
I'm working on modules that have several classes in the vtk component which all require ttkUtils functionality. However, due to a reason I forgot we had to add the content of the ttkUtils.cpp into the ttkUtils.h file. So in my scenario I get "duplicate definition" errors.

I created this PR to separate the implementation from the header again. This also required me to adjust some includes in other modules. If I remember correctly the old version caused linking errors on some platforms. So we have to make sure that everything works (not only the statefiles) before we merge this in.

Best
Jonas

### CODE REVIEW

**Comment by JonasLukasczyk** [comment]
I don't know why Windows can not resolve the external symbols that correspond to the static functions. Can anyone who has experience with the windows build explain this? We will also run into the same issue with the TriangulationRegistry class I'm working on in a separate PR.

**Comment by lhofmann** [comment]
On MSVC, symbols in dynamic libraries are hidden by default, while on GCC they are visible by default (that's why its working on Linux by accident).
The `ttkUtils` class needs the `TTKALGORITHM_EXPORT` attribute, which sets the visibility flags correctly, similar to the `ttkAlgorithm` class.

**Comment by JonasLukasczyk** [comment]
Thanks Lutz! You are the man.

**Comment by JonasLukasczyk** [comment]
Hi Julien, the statefiles and the helloworld standalone work on my machine. I guess someone should also run a quick test on Windows and then we are good to go. After this is merged in I will open a new PR for the TriangulationFactory.

**Comment by julien-tierny** [comment]
@pierre-guillou
would you happen to have a working windows vm at hand?
cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by JonasLukasczyk** [comment]
Then I would have not said: somebody should ;-)

**Comment by pierre-guillou** [comment]
Hi,
Sadly, my windows VM is not set up ATM. I tried to build ParaView 5.8.1 earlier this week and it did not ended well :(
I will retry this afternoon.

**Comment by JonasLukasczyk** [comment]
Any timeline on this since this PR blocks the TriangulationFactory?

**Comment by julien-tierny** [comment]
hi jonas,

thanks for the reminder, but we've just been notified a partial lock down at the universities in paris and that kept us busy.

> Any timeline on this since this PR blocks the TriangulationFactory?
two things:

1) could you update the azure pipeline to use ttkHelloWorldCmd instead of ttkBlandCmd?

2) could you make sure the tests:
- Test TTK Command line
- Test C++ Example
- Test TTKVTK Example
- Test Python Example
- Test pvpython Example
run fine under both MacOs and Windows?
(it seems that those are currently not running with sufficient debug levels)

that'd help get confidence that everything runs fine there.

cheers,
julien
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by pierre-guillou** [comment]
Also, I managed to build this branch on my Windows VM (after spending Friday afternoon rebuilding ParaView 5.8).
I'm still in the process of finding the right set of environment variables to help ParaView find the TTK plugin at run-time.
This should be done soon.
Pierre

**Comment by julien-tierny** [comment]
alright, let's go!

**Pull request merged**
