### PR TITLE
Fix unused warning in ttkOFFReader

### PR DESCRIPTION
**Pull request by mwestphal**
Thanks for contributing to TTK!

Before submitting your pull request, please:

- [X] Review our [Contributor Guidelines](https://github.com/topology-tool-kit/ttk/blob/dev/CONTRIBUTING.md), in particular regarding code formatting (with clang-format) and continuous integration.

- [X] Please provide a quick description of your contributions below:

Fix unsused variable warnings in ttkOFFReader

### CODE REVIEW

**Comment by mwestphal** [comment]
@CharlesGueunet please review

**Review by CharlesGueunet — APPROVED** [review]
If you find any other occurrence of this in other ttkWrapper classes, feel free to fix :)

**Comment by julien-tierny** [comment]
nice :)
what compiler flag did you use to get these warnings?
like @CharlesGueunet mentioned, that can happen in several other spots.

**Comment by julien-tierny** [comment]
thanks mathieu, may that be the first of many :) \0/

**Comment by mwestphal** [comment]
Damn I've been busted :p 

Yes, many other warnings, some that can be covered using vtkNotUsed, some that are not so I was not sure of the right resolution.

I'm using the same as F3D_STRICT_BUILD configuration:

```
 -Wall -Wextra (-Werror)
```

I'd suggest enabling this in your CI and fixing all issues in one go, this will help catch potential issues in the future.

**Pull request merged**
