### PR TITLE
Migration: Step 1

### PR DESCRIPTION
**Pull request by JonasLukasczyk**
This pull requests ports the vtk-only filters to the new architecture. For backwards-compatibility I also opened a new pull request on the ttk-data/dev branch that updates all related statefiles.

These are the most important changes:
* The ported filters use the new debug API
* Instead of specifying array names, the ported VTK filters use the recommended Set/GetInputArrayToProcess API
* The ported VTK modules only depend on ttkAlgorithm
* The XML files of the ported VTK filters now use ${DEBUG_WIDGETS}

### CODE REVIEW

**Comment by JonasLukasczyk** [comment]
Azure encountered an error while compiling the standalone modules. I'm already addressing this issue.

**Comment by JonasLukasczyk** [comment]
I noticed a lot of other pull requests (#344 , #346 , #347 ) also fail to configure TTK on Windows. Apparently the Windows environment is missing boost?

**Comment by julien-tierny** [comment]
hi jonas,

thanks a lot for the PR. I will put it on hold for now though until we progress on ttk-data's PR #27.

cheers
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
thanks for synchronizing that PR with the current dev branch (azure fix).
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by JonasLukasczyk** [comment]
Hi Julien, I merged with the latest dev branch, but please keep in mind that this PR will change the API of the VTK-only TTK filters. So before you actually merge this pull request you should run this fork against the statefiles of the ttk-data PR https://github.com/topology-tool-kit/ttk-data/pull/27.

Best
Jonas

**Comment by julien-tierny** [comment]
on my system, cmake (3.14.6) fails on this PR (the dev branch configures fine)

```
$ cmake ../ -G Ninja -DTTK_ENABLE_KAMIKAZE=ON
-- The CXX compiler identification is GNU 9.2.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release'.
CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:905 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindBoost.cmake:1027 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake/Modules/FindBoost.cmake:1727 (_Boost_MISSING_DEPENDENCIES)
  core/CMakeLists.txt:51 (find_package)


-- Boost version: 1.72.0
-- Found the following Boost libraries:
--   system
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- GraphViz found
-- Found SQLITE3: /usr/lib/libsqlite3.so
-- Found ZFP: /usr/local/lib64/cmake/zfp/zfp-config.cmake (found version "0.5.4") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Python version: 3.6
-- Numpy headers: /usr/lib/python3.6/site-packages/numpy/core/include
-- Found TBB: /usr/include  
-- Found required OSPRay dependency: TBB in /usr/include
-- Found Embree v3.4.0: /usr/local/lib64/libembree3.so.3.4.0
-- Found OSPRay: /usr/local/lib64/libospray.so
-- Found Python3: /usr/lib/libpython3.6m.so (found suitable version "3.6.10", minimum required is "3.6") found components:  Development 
-- Found X11: /usr/include  found components:  Xt 
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found OpenGL: /usr/lib/libGL.so  found components:  OpenGL missing components:  GLX
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found required OSPRay dependency: TBB in /usr/include
-- Found Embree v3.4.0: /usr/local/lib64/libembree3.so.3.4.0
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found required OSPRay dependency: TBB in /usr/include
-- Found Embree v3.4.0: /usr/local/lib64/libembree3.so.3.4.0
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
CMake Error at paraview/CMakeLists.txt:7 (include):
  include called with wrong number of arguments.  include() only takes one
  file.


CMake Error at paraview/CMakeLists.txt:59 (add_paraview_plugin):
  Unknown CMake command "add_paraview_plugin".


-- Configuring incomplete, errors occurred!
See also "/home/julien/Desktop/stuff/prJonas/ttk/build/CMakeFiles/CMakeOutput.log".
See also "/home/julien/Desktop/stuff/prJonas/ttk/build/CMakeFiles/CMakeError.log".
```
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
got it.
for some reason the default branch on your fork is not the "dev" branch.
it configures fine now.
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
hi jonas,

I'm currently going through your PR ttk-data#27.

so far I identified one issue with the current (code) PR.
the module GeometrySmoother fails at using the default point data array "ttkMaskScalarField" for enforcing positional constraints during smoothing.

this issue is visible on bivariateToy.pvsm where the smoothed arcs of the contour tree (bottom right) no longer touch the critical points (because the position of these guys is no longer constrained).
this masking feature is used all over the place (nearly every time there is some smoothing involved), so I suspect this impacts other pvsm files.

cheers
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by JonasLukasczyk** [comment]
That is a great catch. I will check the geometry smoother and make sure he looks by default for this special scalar field.

**Comment by JonasLukasczyk** [comment]
I close this PR and I will iteratively open new PRs for the individual modules of the migration.

**Pull request closed without merging**
