### PR TITLE
renamed IcoSphere to Icosphere

### PR DESCRIPTION
**Pull request by JonasLukasczyk**
Hi Julien,
this PR renames the IcoSphere* modules to Icosphere*. IcoSphereFromPoint now also uses the plural version: IcospheresFromPoints.

NOTE: This requires an update of ttk-data. I'm currently not able to push updates there, but you would only have to run the following search/replace on the statefiles to perform the update yourself:

`sed -i 's/IcoSphere/Icosphere/g' *.pvsm`
`sed -i 's/IcosphereFromPoint/IcospheresFromPoints/g' *.pvsm`

Best
Jonas

### CODE REVIEW

**Comment by JonasLukasczyk** [comment]
MacOS failed to download and extract ParaView xD. I'm not to blame ;-). Is it possible to restart the checks without a commit?

**Comment by JonasLukasczyk** [comment]
@julien-tierny are you willing to merge anyway (see comments above) or should I reopen the PR to restart the checks?

**Comment by julien-tierny** [comment]
hi jonas,

thanks a lot for the PR.

can you please re-sync it with the dev branch?
(charles' PR on vtk9/pv58 migration just got merged)

thanks!
julien
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by JonasLukasczyk** [comment]
Hi Julien,
it was easier to rebase to the last dev branch and rename the filters again. I opened a new PR #367 

Best
Jonas

**Pull request closed without merging**
