### PR TITLE
[api-migration-hackathon] ttkHelloWorld documentation update and additional checks

### PR DESCRIPTION
**Pull request by JonasLukasczyk**

### CODE REVIEW

**Comment by julien-tierny** [comment]
looks good to me.

could you please adjust the already committed documentation accordingly:
- core/vtk/ttkScalarFieldCriticalPoints/ttkScalarFieldCriticalPoints.h
- core/vtk/ttkScalarFieldNormalizer/ttkScalarFieldNormalizer.h

that'd be fantastic.
thanks
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
hi jonas,

this PR is currently queueing in the continuous integration.

can you pull ttk:dev and commit on that branch?
(I disabled a few vms on azure for faster builds).

that will reset and start fewer jobs.

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
@JonasLukasczyk 
can you please propagate your documentation modification suggestion to the other modules already migrated:
core/vtk/ttkIdentifyByScalarField/ttkIdentifyByScalarField.h
core/vtk/ttkIntegralLines/ttkIntegralLines.h
core/vtk/ttkScalarFieldCriticalPoints/ttkScalarFieldCriticalPoints.h
core/vtk/ttkScalarFieldNormalizer/ttkScalarFieldNormalizer.h
core/vtk/ttkScalarFieldSmoother/ttkScalarFieldSmoother.h

thanks.

**Comment by JonasLukasczyk** [comment]
I will edit the remaining documentations and add an explicit error msg if it is not possible to retrieve the input array.

**Comment by julien-tierny** [comment]
hi jonas,

thanks for the edits.

however, for the optional arrays, can you also provide the documentation for the boolean setters? (e.g. setForceInputOffsetScalarField)

cheers,

**Comment by JonasLukasczyk** [comment]
How about this:

///
/// The optional offset array can be specified via the standard VTK call
/// vtkAlgorithm::SetInputArrayToProcess() with the following parameters:
/// \param idx 1 (FIXED: the second array the algorithm requires)
/// \param port 0 (FIXED: first port)
/// \param connection 0 (FIXED: first connection)
/// \param fieldAssociation 0 (FIXED: point data)
/// \param arrayName (DYNAMIC: string identifier of the offset array)
/// NOTE: To use this optional array enable the flag `ForceInputOffsetScalarField`
///

**Comment by julien-tierny** [comment]
looks good.
I'd add a comma :)
/// NOTE: To use this optional array, enable the flag `ForceInputOffsetScalarField`
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
alright, nearly there. I'll take it from here.

**Pull request merged**
