### PR TITLE
Add links to documentation for morsePersistence

### PR DESCRIPTION
**Pull request by eve-le-guillou**
This Pull Request is part of the Hackathon 2021.
It adds links to the documentation of the morsePersistence example for relevant TTK classes.
Some of the links were already added to .xml files.

### CODE REVIEW

**Comment by julien-tierny** [comment]
can you please resolve conflicts?
thanks!

**Review by julien-tierny — CHANGES_REQUESTED** [review]
the `clang-format` continuous integration is failing.
could you please make sure that you use `clang-format` to format your code?
see https://github.com/topology-tool-kit/ttk/blob/dev/CONTRIBUTING.md#2-code-formatting

**Review by julien-tierny — CHANGES_REQUESTED** [review]
also, the example https://topology-tool-kit.github.io/examples/morsePersistence/ involves 5 modules:
- ScalarFieldSmoother
- MorseSmaleComplex
- PersistenceCurve
- PersistenceDiagram
- TopologicalSimplification

so I'd expect 2x5 files to be touched by your commits (5 headers in `core/vtk/` and 5 xml files in `paraview/xmls/`)

it seems we're missing 4 xml files.
can you make sure you're updating these as well?
(maybe you forgot to add them with `git add`)?

**Comment by eve-le-guillou** [comment]
> also, the example https://topology-tool-kit.github.io/examples/morsePersistence/ involves 5 modules:
> 
>     * ScalarFieldSmoother
> 
>     * MorseSmaleComplex
> 
>     * PersistenceCurve
> 
>     * PersistenceDiagram
> 
>     * TopologicalSimplification
> 
> 
> so I'd expect 2x5 files to be touched by your commits (5 headers in `core/vtk/` and 5 xml files in `paraview/xmls/`)
> 
> it seems we're missing 4 xml files. can you make sure you're updating these as well? (maybe you forgot to add them with `git add`)?

To my surprise when I first prepared this PR, the morsePersistence example was already cited in the 4 xml files. I double-checked again today and they are indeed already completed.
It probably has to do with the fact that the md file for this example already existed, but its content corresponded to the dragon example.

**Review by julien-tierny — APPROVED** [review]

**Comment by julien-tierny** [comment]
makes sense! sorry :)

**Pull request merged**
