### PR TITLE
Conda package

### LINKED ISSUE #248: Python bindings
Hello,

Are there separate python bindings for TTK, or is it only usable when Paraview in installed?

There is interest in the Met-Ocean community to use topological methods, and python is part of our regular workflow. However, requiring Paraview (or pvpython) makes it harder to adopt TTK since Paraview is not a usual part of our workflow.

### PR DESCRIPTION
**Pull request by lhofmann**
The TTK Python module is now available as binary package for Linux and OSX on conda-forge: https://anaconda.org/conda-forge/topologytoolkit

This PR adds instructions on how to use the Conda package to the python example README.

Closes #248

### CODE REVIEW

**Comment by julien-tierny** [comment]
hi lutz,

thanks a lot for this great work.
I tried it in a virtual machine and it worked beautifully.
this is really awesome!!

2 quick questions:

- I can see that the official anaconda page (https://anaconda.org/conda-forge/topologytoolkit) only mentions support for linux and macos. this is a naive question but what would it take to have windows support as well? 
the vtk anaconda package seems to support windows and ttk can be built there in principle (https://topology-tool-kit.github.io/installation-windows.html)

- ttk comes with a number of optional dependencies. most of ttk can work without them, but the best support is obtained with these deps installed, in particular: libeigen3-dev, graphviz-dev python3-sklearn, spectra and zfp (see https://topology-tool-kit.github.io/installation.html)
I don't believe these have been pulled when I tried the conda package. do you think this would be possible to add them in? 

cheers,
julien
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by lhofmann** [comment]
There are indeed a few features than can be added to the conda package in the future (btw, changes can be submitted as pull requests to https://github.com/conda-forge/topologytoolkit-feedstock).

* There is no reason, why it couldn't be made to work on Windows. I disabled the windows build, because I currently don't have a Windows environment available to test building TTK. I suspect, that there might be some minor changes necessary.
* graphivz and sqlite are currently the only optional dependencies that are enabled
* In the CI environment, GCC 7.3.0 segfaults during compilation, when Eigen3 is enabled (I haven't been able to isolate the problem yet)
* ZFP and spectra do not seem to have a corresponding conda packages yet and would need to be packaged separately first
* sklearn support, could probably be made to work by following instructions here: https://conda-forge.org/docs/maintainer/knowledge_base.html#building-against-numpy


Currently, the CMake output in conda-forge's CI looks like this:
```
-- The CXX compiler identification is GNU 7.3.0
-- Check for working CXX compiler: $BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-c++
-- Check for working CXX compiler: $BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost 1.70.0 at $PREFIX/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET COMPONENTS system
-- Found boost_headers 1.70.0 at $PREFIX/lib/cmake/boost_headers-1.70.0
-- Found boost_system 1.70.0 at $PREFIX/lib/cmake/boost_system-1.70.0
--   libboost_system.a
-- Adding boost_system dependencies: headers
-- Found Boost: $PREFIX/lib/cmake/Boost-1.70.0/BoostConfig.cmake (found version "1.70.0") found components:  system 
-- Found ZLIB: $PREFIX/lib/libz.so (found version "1.2.11") 
-- GraphViz found
-- Found SQLITE3: $PREFIX/lib/libsqlite3.so
-- ZFP not found, disabling ZFP support in TTK.
CMake Warning at core/CMakeLists.txt:162 (find_package):
  By not providing "FindZFP.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ZFP", but
  CMake did not find one.

  Could not find a package configuration file provided by "ZFP" with any of
  the following names:

    ZFPConfig.cmake
    zfp-config.cmake

  Add the installation prefix of "ZFP" to CMAKE_PREFIX_PATH or set "ZFP_DIR"
  to a directory containing one of the above files.  If "ZFP" provides a
  separate development package or SDK, be sure it has been installed.


-- Could NOT find Eigen3 (missing: Eigen3_DIR)
-- Eigen not found, disabling Eigen support in TTK.
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Python version: 2.7
-- Numpy headers: NOT-FOUND
-- Improper python/numpy setup. Disabling sckikit-learn support in TTK.
-- Spectra not found, disabling Spectra support in TTK.
-- ttk options -----------------------------------------------------------------
-- TTK_ENABLE_CPU_OPTIMIZATION: OFF
-- TTK_ENABLE_EIGEN: OFF
-- TTK_ENABLE_GRAPHVIZ: ON
-- TTK_ENABLE_KAMIKAZE: OFF
-- TTK_ENABLE_MPI: OFF
-- TTK_ENABLE_OPENMP: ON
-- TTK_ENABLE_SCIKIT_LEARN: OFF
-- TTK_ENABLE_SPECTRA: OFF
-- TTK_ENABLE_SQLITE3: ON
-- TTK_ENABLE_ZFP: OFF
-- TTK_ENABLE_ZLIB: ON
-- TTK_ENABLE_64BIT_IDS: OFF
-- ttk build -------------------------------------------------------------------
-- CMAKE_BUILD_TYPE: Release
-- TTK_BUILD_DOCUMENTATION: OFF
-- TTK_BUILD_PARAVIEW_PLUGINS: OFF
-- TTK_BUILD_STANDALONE_APPS: OFF
-- TTK_BUILD_VTK_WRAPPERS: ON
--   VTK_DIR: $PREFIX/lib/cmake/vtk-8.2
--   TTK_BUILD_VTK_PYTHON_MODULE: ON
-- ttk install -----------------------------------------------------------------
-- CMAKE_INSTALL_PREFIX: $PREFIX
-- TTK_PYTHON_MODULE_DIR: lib/python2.7/site-packages
-- TTK_INSTALL_PLUGIN_DIR: 
-- -----------------------------------------------------------------------------
-- Configuring done
-- Generating done
```

**Comment by julien-tierny** [comment]
hi lutz,

thanks for the quick reply.

> There are indeed a few features than can be added to the conda package in the future (btw, changes can be submitted as pull requests to https://github.com/conda-forge/topologytoolkit-feedstock).
understood.

> * There is no reason, why it couldn't be made to work on Windows. I disabled the windows build, because I currently don't have a Windows environment available to test building TTK. I suspect, that there might be some minor changes necessary.
I see. if you have a chance to test that under windows some day, that'd be great.

> * In the CI environment, GCC 7.3.0 segfaults during compilation, when Eigen3 is enabled (I haven't been able to isolate the problem yet)
I see. let's wait for future versions then for eigen support.

> * ZFP and spectra do not seem to have a corresponding conda packages yet and would need to be packaged separately first
makes sense.

> * sklearn support, could probably be made to work by following instructions here: https://conda-forge.org/docs/maintainer/knowledge_base.html#building-against-numpy
I see, I was hoping this would be more trivial. plus, scikit-learn support in ttk is only supported for python3.

I'll merge that in for now and we'll see with future releases if we can expend support to windows and to other optional dependencies.

in the meantime, thanks a lot for this great work lutz, this is highly appreciated!

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by GuillaumeFavelier** [comment]
I tested it and this work is just awesome, thank you!

Using only pure Python code, I was able to obtain the following:

image

I used [PyVista](https://docs.pyvista.org/) for the rendering, I just added those lines at the end of `example.py`:
```py
...
import pyvista as pv # can be done at beginning of the file
p = pv.Plotter()
p.add_mesh(morseSmaleComplex.GetOutput(1))
p.add_mesh(morseSmaleComplex.GetOutput(3))
p.show()
```

**Pull request merged**
