### PR TITLE
Overhauled Cinema Filters

### PR DESCRIPTION
**Pull request by JonasLukasczyk**
CinemaQuery: Multiple table support
CinemaReader: Now automatically prepends database path to FILE columns (removes the need to pass along the absolute database path as a field array and makes it possible to merge multiple tables in the CinemaQuery filter)
CinemaProductReader: Improved memory management
CinemaImaging: Automatic tuning of camera parameters and improved value image generation
CinemaWriter: Self-organizing Cinema databases (replaces existing products and appends new ones) + PNG output support
DepthImageBasedGeometryApproximation: Improved computation
CinemaLayout -> GridLayout: Memory efficient output (only translate and shallow copy where possible)

### CODE REVIEW

**Comment by julien-tierny** [comment]
hi jonas,

thanks a lot.

2 things:

- can you please double-check that this PR still includes the latest features implemented by @pierre-guillou in the ttk-cinema framework? (#288, #287, #283, #282, see the stable branch)

- can you run this PR against all ttk-data examples using cinema features (at least: cinemaReader, geometryApproximation, nestedTrackingGraph, trackingFromOverlap) and double check they run fine (compliant with the following screenshots: https://topology-tool-kit.github.io/gallery.html)

thanks a lot!
cheers
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by JonasLukasczyk** [comment]
Hi,
the branches diverged too much so integrating the other Cinema features will be a huge effort for me. In my opinion it would be much easier to first merge in the new Cinema filters and then @pierre-guillou  can add his features (do you agree Pierre?). Especially since the new Cinema filters already provide some of these features (e.g., multiple input tables for queries, new output format options for the CinemaWriter, ...). 

Some of the state files are now broken because of the Cinema API change (this is why I try hard to merge in the new Cinema API before 1.0 and then keep it stable). This will also be a problem when I push the new for loop filter, block aggregator, and array editor. To always make it possible to run these test would require updating the state files after each iterative merge, which is a lot of overhead in my opinion. I would suggest to keep merging the branches iteratively and agreeing on a milestone on which we update the ttk-data examples. Maybe on a ttk-data dev branch?

**Comment by julien-tierny** [comment]
hi jonas,

thanks for your message.

> the branches diverged too much so integrating the other Cinema features will be a huge effort for me. 
this divergence is really unfortunate, but to some extent, this looks like self-inflicted pain.

> In my opinion it would be much easier to first merge in the new Cinema filters and then @pierre-guillou  can add his features (do you agree Pierre?).
well it seems that at least some discussion between the two of you needs to happen to discuss these features (to identify duplicates if they exist).

I think at this point, it is crucial that you adapt your workflow to avoid such a divergence in the future. in particular, in my opinion, it is the developers' responsibility to make sure that they're always working on the latest version of the official source tree. in short, they should "git pull" the ttk dev branch on a regular basis (typically every day).

in my opinion, pull-requesting commits while ignoring code updates from others go against the basic principles of collaborative software development. asking me to track down the contributors since a given commit, and ask them to handle themselves their updates seems like an unfair work load to be honest.

that being said, @pierre-guillou is a git guru and that may take him no time at all to roll all of that back. let's see what he says but I don't expect him to reply before the end of the christmas break.

but in the long run, you should revisit your workflow. committing code by copy/pasting files does not seem to be good practice and I cannot support that in the long run. so please, reconsider your workflow to make sure you're always up-to-date with the official source tree before you get started on something.

> To always make it possible to run these test would require updating the state files after each iterative merge,
absolutely. this is what we've been doing so far and this is what I recommend to do again this time.

since now the dev branch is the reference source tree for every development, it is crucial that it works out-of-the-box for any body who clones it for further development. so it means that this branch should never be broken. the same goes for its companion examples in the ttk-data repository.

I created a dev branch in ttk-data to follow the organization of the ttk source tree. please PR this branch with updates to ttk-data such that all of these examples run fine with the ttk dev branch.
in my opinion, agreeing on a later milestone for updating all the ttk-data states at once is the worst possible solution and the best way to get something broken for an indefinite time.

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by JonasLukasczyk** [comment]
> this divergence is really unfortunate, but to some extent, this looks like self-inflicted pain.

Obviously, but that resulted from an early merge conflict on the confidential TU-KL fork we always postponed to merge because I wanted to discuss these conflicts first. It just took long until we got this point where we can actually merge the fork.  

> well it seems that at least some discussion between the two of you needs to happen to discuss these features (to identify duplicates if they exist).

Of course

> I think at this point, it is crucial that you adapt your workflow to avoid such a divergence in the future. in particular, in my opinion, it is the developers' responsibility to make sure that they're always working on the latest version of the official source tree. in short, they should "git pull" the ttk dev branch on a regular basis (typically every day).

See above

> in my opinion, pull-requesting commits while ignoring code updates from others go against the basic principles of collaborative software development. asking me to track down the contributors since a given commit, and ask them to handle themselves their updates seems like an unfair work load to be honest. that being said, @pierre-guillou is a git guru and that may take him no time at all to roll all of that back. let's see what he says but I don't expect him to reply before the end of the christmas break. but in the long run, you should revisit your workflow. committing code by copy/pasting files does not seem to be good practice and I cannot support that in the long run. so please, reconsider your workflow to make sure you're always up-to-date with the official source tree before you get started on something.

Of course this is the general work flow, but the new Cinema Filters are a 98% rewrite and I simply suggested that @pierre-guillou features can be added on top of that. I will discuss this with him.  

> absolutely. this is what we've been doing so far and this is what I recommend to do again this time. since now the dev branch is the reference source tree for every development, it is crucial that it works out-of-the-box for any body who clones it for further development. so it means that this branch should never be broken. the same goes for its companion examples in the ttk-data repository. I created a dev branch in ttk-data to follow the organization of the ttk source tree.

Perfect, then I will close this pull request and prepare (bigger) pull requests for ttk dev and ttk-data dev.

Best
Jonas

**Comment by pierre-guillou** [comment]
Hi guys,

Looking at my four merged PRs related to Cinema filters, only #282 seems to be important. #283 and #287 are both 1/2-lines fixes on top of #282, and the features provided in #288 (multiple table queries) should be already provided by this new implementation.

Concerning #282, which use the TopologicalCompression filter as a backend to read (in CinemaProductReader) and write (in CinemaWriter) compressed data, I should be able to port my code with a few modifications (sadly, since the changes are too numerous, git won't help me here). 

A quick glance at the proposed code showed me the method `ttkCinemaProductReader::readFileLocal` that I can use to read my compressed files, and the member variable `ttkCinemaWriter::Mode` that I can extend to support another write back-end.

In the end, maybe one or two hours of copy/paste and subsequent testing for me.

**Comment by julien-tierny** [comment]
hi guys,

thanks a lot @JonasLukasczyk for your reply and thanks @pierre-guillou for your quick feedback.

it looks like the two of you need to discuss possible feature redundancies (such as multiple table queries). 

> In the end, maybe one or two hours of copy/paste and subsequent testing for me.
that'd be fantastic. 
in that case, I'd probably suggest you to PR jonas' branch JonasLukasczyk:devCinema such that he can incorporate your latest edits into his PR to ttk:dev.

thanks a lot for your help you guys.
cheers
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by JonasLukasczyk** [comment]
Hi,
thank you @pierre-guillou, you totally understood which part of the code we have to modify to incorporate your features, and after your summary I think I can actually add these features fairly easily. To be clear:

1) I will add to the CinemaProductReader and the CinemaWriter support for TTK files.
2) The converted CinemaQuery filter already supports multiple tables, but I will adjust their references in the SQL string (currently vtkTable0...) to be compliant with the current dev branch (currently InputTable0...).
3) In the next pull request I will also add the other overhauled pipeline filters (e.g., ttkForEach, ttkBlockAggregator, ...) and update the state files in the ttk-data dev branch to be compliant with the new pull request.

Merry Christmas!
-Jonas

**Pull request closed without merging**
